version: '3.8'

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8088:80"
        volumes:
            - ./laravel:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - postgresql
            - client
        networks:
            - laravel
        restart: always

    php:
        container_name: php
        build:
            context: ./laravel
            dockerfile: Dockerfile
        volumes:
            - ./laravel:/app/laravel
        ports:
            - 8000:8000
        networks:
            - laravel
        restart: always

    client:
        container_name: client
        build:
            context: ./react
            dockerfile: Dockerfile
        ports:
            - 5001:5173
            - 4000:4000
        volumes:
            - ./react:/app/react
        networks:
            - laravel
        restart: always

    postgresql:
        container_name: postgresql
        image: postgres
        environment:
            POSTGRES_DB: PingPongDB
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel
        restart: always

    

    
    

