version: '3.8'

networks:
    app-network:

volumes:
    app-data:

services:

    webserver:
        image: nginx:1.21.6-alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - .docker/nginx:/etc/nginx/conf.d
        depends_on:
            - backend
            - database
        networks:
            app-network:
    
    backend:
        build:
            context: .docker/php
            dockerfile: dockerfile
        container_name: backend
        volumes:
            - ./:/var/www
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            app-network:

    database:
        container_name: PingPong_DB
        image: postgres:13.1-alpine
        environment:
            POSTGRES_DB: PingPongDB
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            PGDATA: /var/lib/postgresql/data
        ports:
            - 5432:5432

        restart: always
    
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgAdmin
        ports:
            - "5050:80"
        depends_on:
            - database
        environment:
            PGADMIN_DEFAULT_EMAIL: d.lapsar16@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password 